import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildPosixHookSpoolLines,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%DORKA_AGENT_HOOK_PORT%"=="" if defined DORKA_AGENT_HOOK_ENDPOINT if exist "%DORKA_AGENT_HOOK_ENDPOINT%" call "%DORKA_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%DORKA_AGENT_HOOK_TOKEN%"=="" if not "%DORKA_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\dorka-dev\\agent-hooks" for /r "%APPDATA%\\dorka-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%DORKA_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\dorka\\agent-hooks" for /r "%APPDATA%\\dorka\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%DORKA_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set DORKA_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%DORKA_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    ...buildPosixHookSpoolLines('command-code'),
    '__dorka_read_ancestor_var() {',
    '  __dorka_name="$1"',
    '  __dorka_pid="${PPID:-}"',
    '  while [ -n "$__dorka_pid" ] && [ "$__dorka_pid" != "0" ] && [ "$__dorka_pid" != "1" ]; do',
    '    __dorka_value=""',
    '    if [ -r "/proc/$__dorka_pid/environ" ]; then',
    '      __dorka_value=$(tr "\\000" "\\n" < "/proc/$__dorka_pid/environ" 2>/dev/null | sed -n "s/^${__dorka_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__dorka_value" ]; then',
    '      __dorka_value=$(ps eww -p "$__dorka_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__dorka_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__dorka_value" ]; then',
    '      printf "%s\\n" "$__dorka_value"',
    '      return 0',
    '    fi',
    '    __dorka_pid=$(ps -o ppid= -p "$__dorka_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__dorka_fill_from_ancestor() {',
    '  __dorka_name="$1"',
    '  case "$__dorka_name" in',
    '    DORKA_AGENT_HOOK_ENDPOINT) [ -z "${DORKA_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    DORKA_AGENT_HOOK_PORT) [ -z "${DORKA_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    DORKA_AGENT_HOOK_TOKEN) [ -z "${DORKA_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    DORKA_AGENT_HOOK_ENV) [ -z "${DORKA_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    DORKA_AGENT_HOOK_VERSION) [ -z "${DORKA_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    DORKA_PANE_KEY) [ -z "${DORKA_PANE_KEY:-}" ] || return 0 ;;',
    '    DORKA_TAB_ID) [ -z "${DORKA_TAB_ID:-}" ] || return 0 ;;',
    '    DORKA_WORKTREE_ID) [ -z "${DORKA_WORKTREE_ID:-}" ] || return 0 ;;',
    '    DORKA_AGENT_LAUNCH_TOKEN) [ -z "${DORKA_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __dorka_value=$(__dorka_read_ancestor_var "$__dorka_name") || return 0',
    '  [ -n "$__dorka_value" ] && export "$__dorka_name=$__dorka_value"',
    '}',
    '__dorka_endpoint_value() {',
    '  __dorka_endpoint_name="$1"',
    '  __dorka_endpoint_path="$2"',
    '  sed -n "s/^${__dorka_endpoint_name}=//p" "$__dorka_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__dorka_fill_from_endpoint_file() {',
    '  __dorka_endpoint_path="$1"',
    '  [ -r "$__dorka_endpoint_path" ] || return 0',
    '  __dorka_endpoint_port=$(__dorka_endpoint_value DORKA_AGENT_HOOK_PORT "$__dorka_endpoint_path")',
    '  if [ -n "${DORKA_AGENT_HOOK_PORT:-}" ] && [ -n "$__dorka_endpoint_port" ] && [ "$__dorka_endpoint_port" != "$DORKA_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __dorka_endpoint_name in DORKA_AGENT_HOOK_PORT DORKA_AGENT_HOOK_TOKEN DORKA_AGENT_HOOK_ENV DORKA_AGENT_HOOK_VERSION; do',
    '    eval "__dorka_current=\\${$__dorka_endpoint_name:-}"',
    '    [ -z "$__dorka_current" ] || continue',
    '    __dorka_endpoint_value=$(__dorka_endpoint_value "$__dorka_endpoint_name" "$__dorka_endpoint_path")',
    '    [ -n "$__dorka_endpoint_value" ] && export "$__dorka_endpoint_name=$__dorka_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Dorka pane/hook metadata, so recover it before posting.',
    'for __dorka_name in DORKA_AGENT_HOOK_ENDPOINT DORKA_AGENT_HOOK_PORT DORKA_AGENT_HOOK_TOKEN DORKA_AGENT_HOOK_ENV DORKA_AGENT_HOOK_VERSION DORKA_PANE_KEY DORKA_TAB_ID DORKA_WORKTREE_ID DORKA_AGENT_LAUNCH_TOKEN; do',
    '  __dorka_fill_from_ancestor "$__dorka_name"',
    'done',
    'if [ -n "$DORKA_AGENT_HOOK_ENDPOINT" ] && [ -r "$DORKA_AGENT_HOOK_ENDPOINT" ]; then',
    '  __dorka_fill_from_endpoint_file "$DORKA_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# DORKA_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$DORKA_AGENT_HOOK_TOKEN" ] && [ -n "$DORKA_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/dorka-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/dorka-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dorka-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dorka-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/dorka/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dorka/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^DORKA_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$DORKA_AGENT_HOOK_PORT" ]; then',
    '      __dorka_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$DORKA_AGENT_HOOK_PORT" ] || [ -z "$DORKA_AGENT_HOOK_TOKEN" ] || [ -z "$DORKA_PANE_KEY" ]; then',
    '  spool_hook_event',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${DORKA_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Dorka-Agent-Hook-Token: ${DORKA_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${DORKA_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${DORKA_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${DORKA_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${DORKA_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${DORKA_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${DORKA_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || spool_hook_event',
    'exit 0',
    ''
  ].join('\n')
}
